my_flask_admin/app/home/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'mosson'
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField
from wtforms.validators import DataRequired, Email, Regexp, EqualTo, ValidationError
from app.models import User


class RegistForm(FlaskForm):
    name = StringField(
        label=u"昵称",
        validators=[
            DataRequired(u"昵称不能为空！")
        ],
        description=u"昵称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": u"请输入昵称！",
        }
    )
    email = StringField(
        label=u"邮箱",
        validators=[
            DataRequired(u"邮箱不能为空！"),
            Email(u"邮箱格式不正确！")
        ],
        description=u"邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": u"请输入邮箱！",
        }
    )
    phone = StringField(
        label=u"手机",
        validators=[
            DataRequired(u"手机号不能为空！"),
            Regexp("1[3458]\\d{9}", message=u"手机格式不正确！")
        ],
        description=u"手机",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": u"请输入手机！",
        }
    )
    pwd = PasswordField(
        label=u"密码",
        validators=[
            DataRequired(u"密码不能为空！")
        ],
        description=u"密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": u"请输入密码！",
        }
    )
    repwd = PasswordField(
        label=u"确认密码",
        validators=[
            DataRequired(u"请输入确认密码！"),
            EqualTo('pwd', message=u"两次密码不一致！")
        ],
        description=u"确认密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": u"请输入确认密码！",
        }
    )
    submit = SubmitField(
        u'注册',
        render_kw={
            "class": "btn btn-lg btn-success btn-block",
        }
    )

    def validate_name(self, field):
        name = field.data
        user = User.query.filter(User.name == name).count()
        if user == 1:
            raise ValidationError(u"名称已经存在")

    def validate_eamil(self, field):
        email = field.data
        email_info = User.query.filter(User.email == email).count()
        if email_info == 1:
            raise ValidationError(u"邮箱已经被注册")
    
    def validate_phone(self, field):
        phone = field.data
        phone_info = User.query.filter(User.phone == phone).count()
        if phone_info == 1:
            raise ValidationError(u"手机号已经被占用")


class LoginForm(FlaskForm):
    name = StringField(
        label=u"账号",
        validators=[
            DataRequired(u"账号不能为空！")
        ],
        description=u"账号",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": u"请输入账号！",
        }
    )
    pwd = PasswordField(
        label=u"密码",
        validators=[
            DataRequired(u"密码不能为空！")
        ],
        description=u"密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": u"请输入密码！",
        }
    )
    submit = SubmitField(
        u'登录',
        render_kw={
            "class": "btn btn-lg btn-primary btn-block",
        }
    )

    def validate_name(self, field):
        name = field.data
        user_obj = User.query.filter_by(name=name).count()
        if user_obj == 0:
            raise ValidationError("账号不存在! ")


class UserdetailForm(FlaskForm):
    name = StringField(
        label=u"账号",
        validators=[
            DataRequired(u"账号不能为空！")
        ],
        description=u"账号",
        render_kw={
            "class": "form-control",
            "placeholder": u"请输入账号！",
        }
    )
    email = StringField(
        label=u"邮箱",
        validators=[
            DataRequired(u"邮箱不能为空！"),
            Email(u"邮箱格式不正确！")
        ],
        description=u"邮箱",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入邮箱！",
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired(u"手机号不能为空！"),
            Regexp("1[3458]\\d{9}", message="手机格式不正确！")
        ],
        description=u"手机",
        render_kw={
            "class": "form-control",
            "placeholder": u"请输入手机！",
        }
    )
    face = FileField(
        label=u"头像",
        validators=[
            DataRequired(u"请上传头像！")
        ],
        description=u"头像",
    )
    info = TextAreaField(
        label=u"简介",
        validators=[
            DataRequired(u"简介不能为空！")
        ],
        description=u"简介",
        render_kw={
            "class": "form-control",
            "rows": 10
        }
    )
    submit = SubmitField(
        u'保存修改',
        render_kw={
            "class": "btn btn-success",
        }
    )


class PwdForm(FlaskForm):
    old_pwd = PasswordField(
        label=u"旧密码",
        validators=[
            DataRequired(u"旧密码不能为空！")
        ],
        description=u"旧密码",
        render_kw={
            "class": "form-control",
            "placeholder": u"请输入旧密码！",
        }
    )
    new_pwd = PasswordField(
        label=u"新密码",
        validators=[
            DataRequired(u"新密码不能为空！"),
        ],
        description=u"新密码",
        render_kw={
            "class": "form-control",
            "placeholder": u"请输入新密码！",
        }
    )
    submit = SubmitField(
        u'修改密码',
        render_kw={
            "class": "btn btn-success",
        }
    )


class CommentForm(FlaskForm):
    content = TextAreaField(
        label=u"内容",
        validators=[
            DataRequired(u"请输入内容！"),
        ],
        description=u"内容",
        render_kw={
            "id": "input_content"
        }
    )
    submit = SubmitField(
        u'提交评论',
        render_kw={
            "class": "btn btn-success",
            "id": "btn-sub"
        }
    )

my_flask_admin/app/home/__init__.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'mosson'
from flask import Blueprint

home = Blueprint("home", __name__)
import app.home.views

my_flask_admin/app/home/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'mosson'
from.import home
from flask import render_template, redirect, url_for, flash, session, request, Response
from app.home.forms import RegistForm, LoginForm, UserdetailForm, PwdForm, CommentForm
from app.models import User, UserLog, Preview, Tag, Movie, Comment, MovieCol
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename
from flask.ext.redis import FlaskRedis
import time
import uuid
import os
import datetime
from app import db, app, rd
from functools import wraps
from sqlalchemy import and_
import json
current_time = int(time.time())


# 登录的装饰器
def user_login_req(func):
    @wraps(func)
    def decorator_func(*args, **kwargs):
        if "user" not in session:
            return redirect(url_for("home.login", next=request.url))
        return func(*args, **kwargs)
    return decorator_func


def change_filename(filename):
    """
    修改文件名称
    """
    fileinfo = os.path.splitext(filename)
    filename = datetime.datetime.now().strftime("%Y%m%d%H%M%S") + \
               str(uuid.uuid4().hex) + fileinfo[-1]
    return filename



@home.route("/<int:page>/", methods=['GET'])
@home.route("/", methods=["GET"])
def index(page=None):
    tags = Tag.query.all()
    page_data = Movie.query
    # 标签
    tid = request.args.get("tid", 0)
    if int(tid) != 0:
        page_data = page_data.filter_by(tag_id=int(tid))
    #星级
    star = request.args.get("star", 0)
    if int(star) != 0:
        page_data = page_data.filter_by(star=int(star))
    # 时间
    time = request.args.get("time", 0)
    if int(time) != 0:
        if int(time) == 1:
            page_data = page_data.order_by(
                Movie.addtime.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.addtime.asc()
            )
    # 播放量
    pm = request.args.get("pm", 0)
    if int(pm) != 0:
        if int(pm) == 1:
            page_data = page_data.order_by(
                Movie.playnum.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.playnum.asc()
            )
    # 评论量
    cm = request.args.get("cm", 0)
    if int(cm) != 0:
        if int(cm) == 1:
            page_data = page_data.order_by(
                Movie.commentnum.desc()
            )
        else:
            page_data = page_data.order_by(
                Movie.commentnum.asc()
            )
    if page is None:
        page = 1
    page_data = page_data.paginate(page=page, per_page=10)
    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )
    return render_template("home/index.html", tags=tags, p=p, page_data=page_data)

@home.route("/login/", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        userobj = User.query.filter(User.name == data['name']).first_or_404()
        # 密码错误时 check_pwd返回flase， 此时not check_pwd(data['name'])
        if not userobj.check_pwd(data["pwd"]):
            flash(u"密码不正确", "err")
            return redirect(url_for("home.login"))
        session["user"] = userobj.name
        session["user_id"] = userobj.id
        userlog = UserLog(
            user_id=userobj.id,
            ip=request.remote_addr,
            addtime=current_time
        )
        db.session.add(userlog)
        db.session.commit()
        return redirect(url_for("home.user_info"))
    return render_template("home/login.html", form=form)

@home.route("/logout/")
@user_login_req
def logout():
    session.pop("user", None)
    session.pop("user_id", None)
    return redirect(url_for("home.login"))

@home.route("/register/", methods=['GET', 'POST'])
def register():
    form = RegistForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            name=data['name'],
            email=data['email'],
            phone=data['phone'],
            pwd=generate_password_hash(data['pwd']),
            uuid=uuid.uuid4().hex,
            addtime=current_time
        
        )
        db.session.add(user)
        db.session.commit()
        flash(u"注册成功", "ok")
    return render_template("home/register.html", form=form)

# 会员中心 修改会员资料
@home.route("/user_info/", methods=['GET', 'POST'])
@user_login_req
def user_info():
    form = UserdetailForm()
    user = User.query.get(int(session["user_id"]))
    form.face.validators = []
    if request.method == "GET": # 赋初值
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data
        if form.face.data != "":
            file_face = secure_filename(form.face.data.filename)
            if not os.path.exists(app.config["FC_DIR"]):
                os.makedirs(app.config["FC_DIR"])
                os.chmod(app.config["FC_DIR"], 'rw')
            user.face = change_filename(file_face)
            form.face.data.save(app.config["FC_DIR"] + user.face)

        name_count = User.query.filter_by(name=data["name"]).count()
        if data["name"] != user.name and name_count == 1:
            flash("昵称已经存在!", "err")
            return redirect(url_for("home.user"))

        email_count = User.query.filter_by(email=data["email"]).count()
        if data["email"] != user.email and email_count == 1:
            flash("邮箱已经存在!", "err")
            return redirect(url_for("home.user"))

        phone_count = User.query.filter_by(phone=data["phone"]).count()
        if data["phone"] != user.phone and phone_count == 1:
            flash("手机已经存在!", "err")
            return redirect(url_for("home.user"))

        user.name = data['name']
        user.email = data['email']
        user.phone = data['phone']
        user.info = data['info']
        db.session.add(user)
        db.session.commit()
        flash(u"修改成功", "ok")
        return redirect(url_for('home.user_info'))
    return render_template("home/user_info.html", form=form, user=user)

@home.route("/modify_pwd/", methods=['GET', 'POST'])
@user_login_req
def modify_pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter(User.name == session["user"]).first()
        if not user.check_pwd(data["old_pwd"]):
            flash(u"旧密码错误", "err")
            return redirect(url_for("home.modify_pwd"))
        user.pwd = generate_password_hash(data['new_pwd'])
        db.session.add(user)
        db.session.commit()
        flash(u"修改密码成功", "ok")
        return redirect(url_for("home.logout"))
    return render_template("home/modify_pwd.html", form=form)

@home.route("/comments/<int:page>/")
@user_login_req
def comments(page=None):
    if page is None:
        page = 1
    print(session['user_id'])
    
    p = Comment.query.join(Movie, Comment.movie_id == Movie.id).add_entity(Movie).join(User, session['user_id'] == User.id).add_entity(User).order_by(Comment.addtime.desc())
    print(p)
    # page_data = Comment.query.join(Movie, Comment.movie_id == Movie.id).add_entity(Movie).join(User, session['user_id'] == User.id).add_entity(User).order_by(Comment.addtime.desc()).paginate(page=page, per_page=10)
    # page_data = User.query.join(Movie, User.id == session['user_id']).add_entity(User).join(Comment, Movie.id == Comment.movie_id).add_entity(Comment).order_by(Comment.addtime.desc()).paginate(page=page, per_page=10)
    page_data = Comment.query.join(Movie, Comment.movie_id == Movie.id).add_entity(Movie).join(User, session['user_id'] == User.id).add_entity(User).paginate(page=page, per_page=10)
    
    return render_template("home/comments.html", page_data=page_data)

@home.route("/loginlog/<int:page>/")
@user_login_req
def loginlog(page=None):
    if page is None:
        page = 1
    page_data = UserLog.query.filter(UserLog.user_id == int(session["user_id"])).order_by(UserLog.addtime.desc()).paginate(page=page, per_page=2)
    return render_template("home/loginlog.html", page_data=page_data)


# 添加电影收藏
@home.route("/moviecol/add/", methods=['GET', 'POST'])
@user_login_req
def moviecol_add():
    uid = request.args.get("uid", "")
    mid = request.args.get("mid", "")
    print(uid, mid, '2222222222')
    moviecol = MovieCol.query.filter(and_(MovieCol.user_id == int(uid), MovieCol.movie_id == int(mid))).count()
    # 已经添加了收藏
    if moviecol == 1:
        data = dict(ok=0)
    if moviecol == 0:
        movie_col = MovieCol(user_id=int(uid), movie_id=int(mid), addtime=current_time)
        db.session.add(movie_col)
        db.session.commit()
        data = dict(ok=1)
    return json.dumps(data)

# 电影收藏
@home.route("/moviecol/<int:page>/", methods=['GET', 'POST'])
@user_login_req
def moviecol(page=None):
    if page is None:
        page = 1
    page_data = MovieCol.query.join(Movie, MovieCol.movie_id == Movie.id).add_entity(Movie).join(User, session['user_id'] == User.id).add_entity(User).paginate(page=page, per_page=10)
    return render_template("home/moviecol.html", page_data=page_data)


# 上映预告
@home.route("/animation/")
def animation():
    data = Preview.query.all()
    return render_template("home/animation.html", data=data)

# 电影搜索页面
@home.route("/search/<int:page>/", methods=['GET', 'POST'])
def search(page=None):
    if page is None:
        page = 1
    key = request.args.get("key", "")
    movie_count = Movie.query.filter(Movie.title.ilike('%' + key + '%')).count()
    page_data = Movie.query.filter(Movie.title.ilike('%' + key + '%')).order_by(Movie.addtime.desc()).paginate(page=page, per_page=10)
    page_data.key = key
    return render_template("home/search.html", key=key, page_data=page_data, movie_count=movie_count)

# 电影播放页面
@home.route("/play/<int:id>/<int:page>/", methods=['GET', 'POST'])
def play(id=None, page=None):
    movie = Movie.query.join(Tag, and_(Movie.tag_id == Tag.id, Movie.id == int(id))).add_entity(Tag).first()
    

my_flask_admin/app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>路飞学院</title>
    <link rel="shortcut icon" href="{{url_for('static', filename='base/images/logo.png')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='base/css/bootstrap-movie.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='base/css/animate.css')}}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
    {% block css %} {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{url_for('home.index')}}" class="navbar-brand" style="width:250px;">
                <img src="{{url_for('static', filename='base/images/logo.png')}}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！"  id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{url_for('home.index')}}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.register')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.logout')}}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.user_info')}}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %} {% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{url_for('static', filename='base/js/jquery.min.js')}}"></script>
<script src="{{url_for('static', filename='base/js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static', filename='base/js/jquery.singlePageNav.min.jsg')}}"></script>
<script src="{{url_for('static', filename='base/js/wow.min.js')}}"></script>
<script src="{{url_for('static', filename='lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function(){
            var key = $("#key_movie").val();
            location.href = "{{url_for('home.search', page=1)}}?key="+ key;
        });
    });

</script>
{%block js%} {%endblock%}
</body>
</html>

my_flask_admin/app/templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>mosson影院</title>
    <link rel="shortcut icon" href="{{url_for('static', filename='base/images/logo.png')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='base/css/bootstrap-movie.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='base/css/animate.css')}}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
    {% block css %} {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{url_for('home.index')}}" class="navbar-brand" style="width:250px;">
                <img src="{{url_for('static', filename='base/images/logo.png')}}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{url_for('home.index')}}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.register')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.logout')}}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{url_for('home.user_info')}}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
{% block content %} {% endblock %}
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;upgrade_flask_demo.mosson.com&nbsp;京ICP备 13046642号-2
                <a href="http://sighttp.qq.com/msgrd?v=1&uin=136782643">请联系mosson</a>
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{url_for('static', filename='base/js/jquery.min.js')}}"></script>
<script src="{{url_for('static', filename='base/js/bootstrap.min.js')}}"></script>
<script src="{{url_for('static', filename='base/js/jquery.singlePageNav.min.jsg')}}"></script>
<script src="{{url_for('static', filename='base/js/wow.min.js')}}"></script>
<script src="{{url_for('static', filename='lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function(){
            var key = $("#key_movie").val();
            location.href = "{{url_for('home.search', page=1)}}?key="+ key;
        });
    });

</script>
{%block js%} {%endblock%}
</body>
</html>

my_flask_admin/app/templates/home/menu.html
<div class="col-md-3">
        <div class="list-group">
            <a id="m1" href="{{url_for('home.user_info')}}" class="list-group-item">
                <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
            </a>
             <a id="m2" href="{{url_for('home.modify_pwd')}}" class="list-group-item">
                <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
            </a>
            <a id="m3" href="{{url_for('home.comments', page=1)}}" class="list-group-item">
                <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
            </a>
            <a id="m4" href="{{url_for('home.loginlog', page=1)}}" class="list-group-item">
                <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
            </a>
            <a id="m5" href="{{url_for('home.moviecol', page=1)}}" class="list-group-item">
                <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
            </a>
        </div>
    </div>

my_flask_admin/app/templates/home/search.html
{% extends "home/home.html"%}
{% import "ui/s_page.html" as pg %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <ol class="breadcrumb" style="margin-top:6px;">
            <li>与"{{key}}"有关的电影，共{{movie_count}}部</li>
        </ol>
    </div>
    <div class="col-md-12">
        {% for i in page_data.items %}
        <div class="media">
            <div class="media-left">
                <a href="{{url_for('home.play', id=i.id, page=1)}}">
                    <img class="media-object" style="width:131px;height:83px" src="{{url_for('static', filename='uploads/'+i.logo)}}" alt="{{i.title}}">
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">{{i.title}}
                    <a href="{{url_for('home.play', id=i.id, page=1)}}" class="label label-primary pull-right">
                        <span class="glyphicon glyphicon-play"></span>播放影片</a>
                </h4>
                {{i.info}}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-12 text-center">
        {{ pg.page(page_data,'home.search') }}
    </div>
</div>
{% endblock %}